name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/logintester:latest
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/logintester:latest
